# Generated by Django 5.2.7 on 2025-10-08 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=13, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('publicacao', models.DateField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estoque', models.IntegerField()),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pratica04.editora')),
            ],
        ),
        migrations.CreateModel(
            name='Publica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pratica04.autor')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pratica04.livro')),
            ],
            options={
                'unique_together': {('livro', 'autor')},
            },
        ),
        migrations.AddField(
            model_name='livro',
            name='autores',
            field=models.ManyToManyField(related_name='livros', through='pratica04.Publica', to='pratica04.autor'),
        ),
    ]
